server:
  port: 8091
logging:
  config: classpath:logback-admin.xml
log:
  level:
    #日志级别从低到高分为：
    #  配置TRACE < DEBUG < INFO < WARN < ERROR < FATAL
    root: INFO
    my: DEBUG
  file: logs/admin-server.log
  maxsize: 10MB
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:dbtest
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      platform: h2
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
  banner:
    charset: UTF-8
    location: classpath:banner.txt
knife4j:
  enable: true
  setting:
    # default lang
    language: en-US
    # footer
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: MIT | [Java 全栈](https://pdai.tech)
    # models
    enableSwaggerModels: true
    swaggerModelName: My Models
